id = "make"
name = "Make"
authors = ["Caius Durling <dev@caius.name>"]
description = "Makefile syntax highlighting"
version = "0.0.1"
schema_version = 1
repository = "https://github.com/caius/zed-make"

[grammars.make]
repository = "https://github.com/caius/tree-sitter-make"
commit = "b35c2714e73d2846b26061b06cda4fa56d61e3a5"
